export const SITE_PHOTOS = [
  "/images/cs7/op-028.jpg",
  "/images/cs7/op-023.jpg",
  "/images/cs7/op-021.jpg",
  "/images/cs7/op-026.jpg",
  "/images/wp/wp-bg-61.jpg",
  "/images/trench.jpg",
  "/images/seabed.jpg",
  "/images/seabed2.jpg",
  "/images/cs7/cs7-underwater.jpg",
  "/images/silverbars.jpg",
  "/images/cs7/op-025.jpg",
  "/images/scuba.jpg",
  "/images/cs7/cs7-seats.jpg",
  "/images/vessel.jpg",
  "/images/cs7/cs7-camera.jpg",
  "/images/cs7/cs7-front.jpg",
  "/images/cs7/cs7-onboard.jpg",
  "/images/cs7/op-024.jpg",
  "/images/cs7/op-022.jpg",
  "/images/wp/wp-bg-62.jpg",
  "/images/cs7/cs7-in-01.jpg",
  "/images/cs7/cs7-in-03.jpg",
  "/images/wp-form-d.jpg",
  "/images/wp-form-c.jpg",
  "/images/wp-form-a.jpg",
  "/images/cs7/cs7-chairs.jpg",
  "/images/cs7/cs7-lamps.jpg",
  "/images/wp-form-b.jpg",
] as const;

export const CRITICAL_PHOTOS = [
  "/images/cs7/op-028.jpg",
  "/images/cs7/op-025.jpg",
  "/images/scuba.jpg",
  "/images/cs7/op-023.jpg",
  "/images/cs7/op-021.jpg",
  "/images/vessel.jpg",
] as const;
